cervezas_homepage:
    path:     /
    defaults: { _controller: cervezasBundle:Default:index }
cervezas_detalle:
    path:     /detalle/{idCerveza}
    defaults: { _controller: cervezasBundle:Default:detalle }
